#ifndef __REMOTE_ACT_ERROR_H__
#define __REMOTE_ACT_ERROR_H__

enum {
	RACT_OK = 0,
	RACT_CANNOT_OPEN_SOCKET = -1,
	RACT_CANNOT_BIND_SOCKET = -2,
	RACT_CANNOT_LAUNCH_ACCEPT_THREAD = -3,
	RACT_COMMAND_OK = 1,
	RACT_COMMAND_PONG = 2,
	RACT_COMMAND_ERROR = 3,
	RACT_UNKNOWN_COMMAND = -4,
	RACT_CANNOT_ADD_COMMAND = -5
};

#endif // __REMOTE_RACT_ERROR_H__
